#!/bin/bash

# Rausach V3 - Quick Deployment Reference
# ==========================================

echo "========================================="
echo "   Rausach V3 - Deployment Commands"
echo "========================================="
echo ""
echo "📦 DEPLOYMENT INFO:"
echo "   Frontend: http://116.118.49.243:12100"
echo "   Backend:  http://116.118.49.243:12101"
echo "   Database: rausachv3@116.118.49.243:55432"
echo "   Path:     /opt/rausachv3"
echo ""
echo "🚀 QUICK COMMANDS:"
echo ""
echo "1. Full Deploy (Build + Upload + Deploy):"
echo "   ./deploy-v3.sh all"
echo ""
echo "2. Build Only:"
echo "   ./deploy-v3.sh build"
echo ""
echo "3. Build API Only:"
echo "   ./deploy-v3.sh api"
echo ""
echo "4. Build Frontend Only:"
echo "   ./deploy-v3.sh frontend"
echo ""
echo "5. Upload to Server:"
echo "   ./deploy-v3.sh upload"
echo ""
echo "6. Deploy on Server:"
echo "   ./deploy-v3.sh deploy"
echo ""
echo "📝 SERVER COMMANDS:"
echo ""
echo "View Logs:"
echo "   ssh root@116.118.49.243 'cd /opt/rausachv3 && docker-compose logs -f'"
echo ""
echo "Check Status:"
echo "   ssh root@116.118.49.243 'cd /opt/rausachv3 && docker-compose ps'"
echo ""
echo "Restart Services:"
echo "   ssh root@116.118.49.243 'cd /opt/rausachv3 && docker-compose restart'"
echo ""
echo "Stop Services:"
echo "   ssh root@116.118.49.243 'cd /opt/rausachv3 && docker-compose down'"
echo ""
echo "Start Services:"
echo "   ssh root@116.118.49.243 'cd /opt/rausachv3 && docker-compose up -d'"
echo ""
echo "========================================="
