version: '3.8'

services:
  api:
    image: rausach-backend:latest
    container_name: rausachv3-api
    restart: always
    ports:
      - "12101:3331"
    environment:
      - DATABASE_URL=postgresql://AWois79wFA1bxMK:7bhNHJcSEbWln9v@116.118.49.243:55432/rausachv3?schema=public&connection_limit=25&pool_timeout=60&connect_timeout=20
      - GOOGLE_CLIENT_ID=897974685698-efprsqffgop935h5d5l2lidle1go9i17.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - BASE_URL=https://v3.rausachtrangia.com
      - SERVER_URL=https://apiv3.rausachtrangia.com 
      - PORT=3331
      - JWT_SECRET=supersecret
      - REDIS_HOST=116.118.49.243
      - REDIS_PORT=56379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_TTL=3600
      - MINIO_ENDPOINT=storage.rausachtrangia.com
      - MINIO_PORT=59000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=RC4hWSS4V6QIcfl
      - MINIO_SECRET_KEY=LEOZHZwjaasTTKk
      - MINIO_ROOT_USER=RC4hWSS4V6QIcfl
      - MINIO_ROOT_PASSWORD=LEOZHZwjaasTTKk
      - MINIO_BUCKET_NAME=uploads
      - MINIO_BUCKET=uploads
      - MINIO_REGION=us-east-1
      - MINIO_PUBLIC_URL=http://storage.rausachtrangia.com:59000
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    networks:
      - rausachv3-network

  frontend:
    image: rausach-frontend:latest
    container_name: rausachv3-frontend
    restart: always
    ports:
      - "12100:4301"
    environment:
      - NODE_ENV=production
    networks:
      - rausachv3-network

networks:
  rausachv3-network:
    driver: bridge
