-- CreateTable
CREATE TABLE "dichvu" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "codeOld" TEXT,
    "docCode" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "phone2" TEXT,
    "birthday" TIMESTAMP(3),
    "gender" TEXT,
    "address" TEXT,
    "commune" TEXT,
    "district" TEXT,
    "city" TEXT,
    "serviceId" INTEGER NOT NULL,
    "serviceTypeId" INTEGER NOT NULL,
    "serviceCode" TEXT NOT NULL,
    "tabId" INTEGER NOT NULL,
    "tabCode" TEXT NOT NULL,
    "comboId" INTEGER NOT NULL,
    "comboCode" TEXT,
    "serviceName" TEXT NOT NULL,
    "timeIndex" TEXT,
    "timeToTreatment" INTEGER NOT NULL,
    "teethChoosing" TEXT,
    "priceUnit" DOUBLE PRECISION NOT NULL,
    "quantity" DOUBLE PRECISION NOT NULL,
    "discount" DOUBLE PRECISION NOT NULL,
    "priceRoot" DOUBLE PRECISION NOT NULL,
    "priceDiscounted" DOUBLE PRECISION NOT NULL,
    "doctor" INTEGER NOT NULL,
    "doctor2" INTEGER NOT NULL,
    "doctor3" INTEGER NOT NULL,
    "doctor4" INTEGER NOT NULL,
    "assistant" INTEGER NOT NULL,
    "assistant2" INTEGER NOT NULL,
    "assistant3" INTEGER NOT NULL,
    "assistant4" INTEGER NOT NULL,
    "technician" INTEGER NOT NULL,
    "technician2" INTEGER NOT NULL,
    "timeTreatIndex" INTEGER NOT NULL,
    "percent" DOUBLE PRECISION NOT NULL,
    "percentNew" DOUBLE PRECISION NOT NULL,
    "percentStage" DOUBLE PRECISION NOT NULL,
    "percentNewStage" DOUBLE PRECISION NOT NULL,
    "note" TEXT,
    "content" TEXT,
    "contentNext" TEXT,
    "symptoms" TEXT,
    "treatDateNext" TIMESTAMP(3),
    "branchId" INTEGER NOT NULL,
    "createdDate" TIMESTAMP(3) NOT NULL,
    "createdBy" INTEGER NOT NULL,
    "modifiedDate" TIMESTAMP(3) NOT NULL,
    "modifiedBy" INTEGER NOT NULL,
    "state" INTEGER NOT NULL,

    CONSTRAINT "dichvu_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "dichvu_code_key" ON "dichvu"("code");
