-- CreateTable
CREATE TABLE "Hoadon" (
    "id" TEXT NOT NULL,
    "nbmst" TEXT NOT NULL,
    "khmshdon" INTEGER,
    "khhdon" TEXT,
    "shdon" INTEGER,
    "cqt" TEXT,
    "cttkhac" JSONB,
    "dvtte" TEXT,
    "hdon" TEXT,
    "hsgcma" TEXT,
    "hsgoc" TEXT,
    "hthdon" INTEGER,
    "htttoan" INTEGER,
    "idtbao" TEXT,
    "khdon" TEXT,
    "khhdgoc" TEXT,
    "khmshdgoc" TEXT,
    "lhdgoc" TEXT,
    "mhdon" TEXT,
    "mtdiep" TEXT,
    "mtdtchieu" TEXT,
    "nbdchi" TEXT,
    "nbhdktngay" TIMESTAMP(3),
    "nbhdktso" TEXT,
    "nbhdso" TEXT,
    "nblddnbo" TEXT,
    "nbptvchuyen" TEXT,
    "nbstkhoan" TEXT,
    "nbten" TEXT,
    "nbtnhang" TEXT,
    "nbtnvchuyen" TEXT,
    "ncma" TIMESTAMP(3),
    "ncnhat" TIMESTAMP(3),
    "ngcnhat" TEXT,
    "nky" TIMESTAMP(3),
    "nmdchi" TEXT,
    "nmmst" TEXT,
    "nmstkhoan" TEXT,
    "nmten" TEXT,
    "nmtnhang" TEXT,
    "nmtnmua" TEXT,
    "ntao" TIMESTAMP(3),
    "ntnhan" TIMESTAMP(3),
    "pban" TEXT,
    "ptgui" INTEGER,
    "shdgoc" TEXT,
    "tchat" INTEGER,
    "tdlap" TIMESTAMP(3),
    "tgia" INTEGER,
    "tgtcthue" INTEGER,
    "tgtthue" INTEGER,
    "tgtttbchu" TEXT,
    "tgtttbso" INTEGER,
    "thdon" TEXT,
    "thlap" INTEGER,
    "thttlphi" JSONB,
    "tlhdon" TEXT,
    "ttcktmai" INTEGER,
    "tthai" INTEGER,
    "tttbao" INTEGER,
    "ttxly" INTEGER,
    "tvandnkntt" TEXT,
    "mhso" TEXT,
    "ladhddt" INTEGER,
    "mkhang" TEXT,
    "nbsdthoai" TEXT,
    "nbdctdtu" TEXT,
    "nbfax" TEXT,
    "nbwebsite" TEXT,
    "nbcks" TEXT,
    "nmsdthoai" TEXT,
    "nmdctdtu" TEXT,
    "nmcmnd" TEXT,
    "nmcks" TEXT,
    "bhphap" INTEGER,
    "hddunlap" TEXT,
    "gchdgoc" TEXT,
    "tbhgtngay" TIMESTAMP(3),
    "bhpldo" TEXT,
    "bhpcbo" TEXT,
    "bhpngay" TIMESTAMP(3),
    "tdlhdgoc" TEXT,
    "tgtphi" INTEGER,
    "unhiem" TEXT,
    "mstdvnunlhdon" TEXT,
    "tdvnunlhdon" TEXT,
    "nbmdvqhnsach" TEXT,
    "nbsqdinh" TEXT,
    "nbncqdinh" TEXT,
    "nbcqcqdinh" TEXT,
    "nbhtban" TEXT,
    "nmmdvqhnsach" TEXT,
    "nmddvchden" TEXT,
    "nmtgvchdtu" TEXT,
    "nmtgvchdden" TEXT,
    "nbtnban" TEXT,
    "dcdvnunlhdon" TEXT,
    "dksbke" TEXT,
    "dknlbke" TEXT,
    "thtttoan" TEXT,
    "msttcgp" TEXT,
    "gchu" TEXT,
    "kqcht" TEXT,
    "hdntgia" TEXT,
    "tgtkcthue" TEXT,
    "tgtkhac" INTEGER,
    "nmshchieu" TEXT,
    "nmnchchieu" TEXT,
    "nmnhhhchieu" TEXT,
    "nmqtich" TEXT,
    "ktkhthue" TEXT,
    "hdhhdvu" TEXT,
    "qrcode" TEXT,
    "ttmstten" TEXT,
    "ladhddtten" TEXT,
    "hdxkhau" TEXT,
    "hdxkptquan" TEXT,
    "hdgktkhthue" TEXT,
    "hdonLquans" JSONB,
    "tthdclquan" BOOLEAN,
    "pdndungs" JSONB,
    "hdtbssrses" JSONB,
    "hdTrung" TEXT,
    "isHDTrung" BOOLEAN,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Hoadon_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "HoadonChitiet" (
    "id" TEXT NOT NULL,
    "idhdon" TEXT NOT NULL,
    "dgia" INTEGER,
    "dvtinh" TEXT,
    "ltsuat" TEXT,
    "sluong" INTEGER,
    "stbchu" TEXT,
    "stckhau" INTEGER,
    "stt" INTEGER,
    "tchat" INTEGER,
    "ten" TEXT,
    "thtcthue" INTEGER,
    "thtien" INTEGER,
    "tlckhau" INTEGER,
    "tsuat" DOUBLE PRECISION,
    "tthue" INTEGER,
    "sxep" INTEGER,
    "dvtte" TEXT,
    "tgia" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HoadonChitiet_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "HoadonChitiet_idhdon_idx" ON "HoadonChitiet"("idhdon");

-- AddForeignKey
ALTER TABLE "HoadonChitiet" ADD CONSTRAINT "HoadonChitiet_idhdon_fkey" FOREIGN KEY ("idhdon") REFERENCES "Hoadon"("id") ON DELETE CASCADE ON UPDATE CASCADE;
