-- AlterTable
ALTER TABLE "PhieuKhoSanpham" ADD COLUMN     "slgiao" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "slhuy" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sltra" DOUBLE PRECISION NOT NULL DEFAULT 0;
