-- AlterTable
ALTER TABLE "Donhangsanpham" ADD COLUMN     "giaban" DECIMAL(20,2) NOT NULL DEFAULT 0,
ADD COLUMN     "ttsauvat" DECIMAL(20,2) NOT NULL DEFAULT 0,
ADD COLUMN     "vat" DECIMAL(20,2) NOT NULL DEFAULT 0;
