-- CreateTable
CREATE TABLE "revenues" (
    "id" SERIAL NOT NULL,
    "source_id" TEXT NOT NULL,
    "code" TEXT,
    "branchId" INTEGER,
    "custCode" TEXT,
    "custName" TEXT,
    "custPhone" TEXT,
    "custAddress" TEXT,
    "custBirthday" TIMESTAMP(3),
    "depositId" INTEGER,
    "paidAmount" DOUBLE PRECISION,
    "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "depositAmountUsing" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "debtAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "methodName" TEXT,
    "content" TEXT,
    "serviceId" INTEGER NOT NULL DEFAULT 0,
    "isProduct" INTEGER NOT NULL DEFAULT 0,
    "quantity" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "priceRoot" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "priceUnit" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "price" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "amount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "timeToTreatment" INTEGER NOT NULL DEFAULT 0,
    "percentOfService" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "treatIndex" INTEGER NOT NULL DEFAULT 0,
    "type" TEXT,
    "typeName" TEXT,
    "consultId1" INTEGER NOT NULL DEFAULT 0,
    "consultId2" INTEGER NOT NULL DEFAULT 0,
    "consultId3" INTEGER NOT NULL DEFAULT 0,
    "consultId4" INTEGER NOT NULL DEFAULT 0,
    "techId" INTEGER NOT NULL DEFAULT 0,
    "tele1" INTEGER NOT NULL DEFAULT 0,
    "tele2" INTEGER NOT NULL DEFAULT 0,
    "createdDate" TIMESTAMP(3),
    "createdBy" TEXT,
    "modifiedDate" TIMESTAMP(3),
    "state" INTEGER,
    "extractedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "revenues_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "revenues_source_id_key" ON "revenues"("source_id");
