-- AlterTable
ALTER TABLE "Dathang" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "printCount" INTEGER DEFAULT 0,
ADD COLUMN     "updatedAt" TIMESTAMP(3);
