import { AfterViewInit, ChangeDetectionStrategy, Component, computed, effect, inject, ViewChild } from '@angular/core';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { MatSort, MatSortModule } from '@angular/material/sort';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { MatDrawer, MatSidenavModule } from '@angular/material/sidenav';
import { Router, RouterLink, RouterOutlet } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatSelectModule } from '@angular/material/select';
import { CommonModule } from '@angular/common';
import { MatSnackBar } from '@angular/material/snack-bar';
import { FormsModule } from '@angular/forms';
import { MatTooltipModule } from '@angular/material/tooltip';
import { SanphamService } from '../sanpham.service';
import { MatMenuModule } from '@angular/material/menu';
import { readExcelFile, writeExcelFile } from '../../../shared/utils/exceldrive.utils';
import { ConvertDriveData, convertToSlug, GenId } from '../../../shared/utils/shared.utils';
import { GoogleSheetService } from '../../../shared/googlesheets/googlesheets.service';
import { removeVietnameseAccents } from '../../../shared/utils/texttransfer.utils';
import { NhacungcapService } from '../../nhacungcap/nhacungcap.service';
@Component({
  selector: 'app-listsanpham',
  templateUrl: './listsanpham.component.html',
  styleUrls: ['./listsanpham.component.scss'],
  imports: [
    MatFormFieldModule,
    MatInputModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatMenuModule,
    MatSidenavModule,
    RouterOutlet,
    MatIconModule,
    MatButtonModule,
    MatSelectModule,
    CommonModule,
    FormsModule,
    MatTooltipModule,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ListSanphamComponent {
  Detail: any = {};
  displayedColumns: string[] = [
    'masp',
    'title',
    'title2',
    'giagoc',
    'dvt',
    'soluong',
    'soluongkho',
    'haohut',
    'subtitle',
    'ghichu',
    'createdAt',
  ];
  ColumnName: any = {
    masp: 'Mã Sản Phẩm',
    title: 'Tên Sản Phẩm',
    title2: 'Tên Sản Phẩm 2',
    giagoc: 'Giá Gốc',
    dvt: 'Đơn Vị Tính',
    soluong: 'SL',
    soluongkho: 'SL Kho',
    haohut: 'Hao Hụt',
    subtitle: 'Gợi ý',
    ghichu: 'Ghi Chú',
    createdAt: 'Ngày Tạo'
  };
  FilterColumns: any[] = JSON.parse(
    localStorage.getItem('SanphamColFilter') || '[]'
  );
  Columns: any[] = [];
  @ViewChild(MatPaginator) paginator!: MatPaginator;
  @ViewChild(MatSort) sort!: MatSort;
  @ViewChild('drawer', { static: true }) drawer!: MatDrawer;
  filterValues: { [key: string]: string } = {};
  private _SanphamService: SanphamService = inject(SanphamService);
  private _breakpointObserver: BreakpointObserver = inject(BreakpointObserver);
  private _GoogleSheetService: GoogleSheetService = inject(GoogleSheetService);
  private _NhacungcapService: NhacungcapService = inject(NhacungcapService);
  private _router: Router = inject(Router);
  Listsanpham:any = this._SanphamService.ListSanpham;
  dataSource = new MatTableDataSource([]);
  sanphamId:any = this._SanphamService.sanphamId;
  _snackBar: MatSnackBar = inject(MatSnackBar);
  CountItem: any = 0;
  isSearch: boolean = false;
  listNCC1:any[] =[];
  constructor() {
    this.displayedColumns.forEach(column => {
      this.filterValues[column] = '';
    });
  }
  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();
    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }
  async ngOnInit(): Promise<void> {    
    await this._SanphamService.getAllSanpham();
    this.CountItem = this.Listsanpham().length;
    this.dataSource = new MatTableDataSource(this.Listsanpham());
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
    this.initializeColumns();
    this.setupDrawer();
    this.paginator._intl.itemsPerPageLabel = 'Số lượng 1 trang';
    this.paginator._intl.nextPageLabel = 'Tiếp Theo';
    this.paginator._intl.previousPageLabel = 'Về Trước';
    this.paginator._intl.firstPageLabel = 'Trang Đầu';
    this.paginator._intl.lastPageLabel = 'Trang Cuối';
  }
  // async UpdateNcc(){
  //   const listNCC = await this._NhacungcapService.getAllNhacungcap();    
  //   this.initSP.forEach(async (v:any) => {
  //      v.Sanpham =[]
  //       for (let i = 1; i <= 30; i++) {
  //         const tenspKey = `tensp${i}`;
  //         const idKey = `id${i}`;
  //         if (v[tenspKey] === '') {
  //           break; // Dừng vòng lặp nếu không còn tên sản phẩm
  //         }
  //         const item = this.Listsanpham().find((v1: any) => removeVietnameseAccents(v1.title) === removeVietnameseAccents(v[tenspKey]))
  //         if(item){
  //           v[idKey] = item.id; 
  //           v.Sanpham.push(item) 
  //         }  
  //       }
  //   });
  //   this.listNCC1 = this.initSP.map((v:any) => {
  //     const item = listNCC.find((v1:any) => v1.mancc === v.mancc);
  //     if (item) {
  //       return {
  //         ...item,
  //         Sanpham: v.Sanpham,
  //       };
  //     }
  //     else {
  //     console.log('Không tìm thấy nhà cung cấp cho sản phẩm:', v);
  //     }
  //   })
  //   this.listNCC1.forEach(async (v:any) => {
  //       await this._NhacungcapService.updateNhacungcap(v);
  //   })
  // }
  async refresh() {
   await this._SanphamService.getAllSanpham();
  }
  private initializeColumns(): void {
    this.Columns = Object.keys(this.ColumnName).map((key) => ({
      key,
      value: this.ColumnName[key],
      isShow: true,
    }));
    if (this.FilterColumns.length === 0) {
      this.FilterColumns = this.Columns;
    } else {
      localStorage.setItem('SanphamColFilter',JSON.stringify(this.FilterColumns)
      );
    }
    this.displayedColumns = this.FilterColumns.filter((v) => v.isShow).map(
      (item) => item.key
    );
    this.ColumnName = this.FilterColumns.reduce((obj, item) => {
      if (item.isShow) obj[item.key] = item.value;
      return obj;
    }, {} as Record<string, string>);
  }

  private setupDrawer(): void {
    this._breakpointObserver
      .observe([Breakpoints.Handset])
      .subscribe((result) => {
        if (result.matches) {
          this.drawer.mode = 'over';
          this.paginator.hidePageSize = true;
        } else {
          this.drawer.mode = 'side';
        }
      });
  }
  toggleColumn(item: any): void {
    const column = this.FilterColumns.find((v) => v.key === item.key);
    if (column) {
      column.isShow = !column.isShow;
      this.updateDisplayedColumns();
    }
  }
  @memoize()
  FilterHederColumn(list:any,column:any)
  {
    const uniqueList = list.filter((obj: any, index: number, self: any) => 
      index === self.findIndex((t: any) => t[column] === obj[column])
    );
    return uniqueList
  }
  @Debounce(300)
  doFilterHederColumn(event: any, column: any): void {
    this.dataSource.filteredData = this.Listsanpham().filter((v: any) => removeVietnameseAccents(v[column]).includes(event.target.value.toLowerCase())||v[column].toLowerCase().includes(event.target.value.toLowerCase()));  
    const query = event.target.value.toLowerCase();  
  }
  ListFilter:any[] =[]
  ChosenItem(item:any,column:any)
  {
    const CheckItem = this.dataSource.filteredData.filter((v:any)=>v[column]===item[column]);
    const CheckItem1 = this.ListFilter.filter((v:any)=>v[column]===item[column]);
    if(CheckItem1.length>0)
    {
      this.ListFilter = this.ListFilter.filter((v) => v[column] !== item[column]);
    }
    else{
      this.ListFilter = [...this.ListFilter,...CheckItem];
    }
  }
  ChosenAll(list:any)
  {
    list.forEach((v:any) => {
      const CheckItem = this.ListFilter.find((v1)=>v1.id===v.id)?true:false;
      if(CheckItem)
        {
          this.ListFilter = this.ListFilter.filter((v) => v.id !== v.id);
        }
        else{
          this.ListFilter.push(v);
        }
    });
  }
  ResetFilter()
  {
    this.ListFilter = this.Listsanpham();
    this.dataSource.data = this.Listsanpham();
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }
  EmptyFiter()
  {
    this.ListFilter = [];
  }
  CheckItem(item:any)
  {
    return this.ListFilter.find((v)=>v.id===item.id)?true:false;
  }
  ApplyFilterColum(menu:any)
  {    

    this.dataSource.data = this.Listsanpham().filter((v: any) => this.ListFilter.some((v1) => v1.id === v.id));
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
    menu.closeMenu();
  }
  private updateDisplayedColumns(): void {
    this.displayedColumns = this.FilterColumns.filter((v) => v.isShow).map(
      (item) => item.key
    );
    this.ColumnName = this.FilterColumns.reduce((obj, item) => {
      if (item.isShow) obj[item.key] = item.value;
      return obj;
    }, {} as Record<string, string>);
    localStorage.setItem('SanphamColFilter',JSON.stringify(this.FilterColumns)
    );
  }
  doFilterColumns(event: any): void {
    const query = event.target.value.toLowerCase();
    this.FilterColumns = this.Columns.filter((v) =>
      v.value.toLowerCase().includes(query)
    );
  }
  create(): void {
    this.drawer.open();
    this._router.navigate(['admin/sanpham', 0]);
  }
  goToDetail(item: any): void {
     this._SanphamService.setSanphamId(item.id);
    this.drawer.open();
    this._router.navigate(['admin/sanpham', item.id]);
  }
  async LoadDrive() {
    const DriveInfo = {
      IdSheet: '15npo25qyH5FmfcEjl1uyqqyFMS_vdFnmxM_kt0KYmZk',
      SheetName: 'SPImport',
      ApiKey: 'AIzaSyD33kgZJKdFpv1JrKHacjCQccL_O0a2Eao',
    };
   const result: any = await this._GoogleSheetService.getDrive(DriveInfo);
   const data = ConvertDriveData(result.values);
   console.log(data);
   this.DoImportData(data);
  }
  DoImportData(data:any)
  {
    console.log(data);
    
    const transformedData = data.map((v: any) => ({
      title: v.title?.trim()||'',
      title2: v.title2?.trim()||'',
      subtitle: v.subtitle?.trim()||'',
      masp: v.masp?.trim()||'',
      giagoc: Number(v.giagoc)||0,
      dvt: v.dvt?.trim()||'',
      soluong: Number(v.soluong)||0,
      soluongkho: Number(v.soluongkho)||0,
      haohut: Number(v.haohut)||0,
      ghichu: v.ghichu?.trim()||'',
   }));

   // Filter out duplicate masp values
   const uniqueData = transformedData.filter((value:any, index:any, self:any) => 
      index === self.findIndex((t:any) => (
        t.masp === value.masp
      ))
   )
    const listId2 = uniqueData.map((v: any) => v.masp);
    const listId1 = this._SanphamService.ListSanpham().map((v: any) => v.masp);
    const listId3 = listId2.filter((item:any) => !listId1.includes(item));
    const createuppdateitem = uniqueData.map(async (v: any) => {
        const item = this._SanphamService.ListSanpham().find((v1) => v1.masp === v.masp);
        if (item) {
          const item1 = { ...item, ...v };
          await this._SanphamService.updateSanpham(item1);
        }
        else{
          await this._SanphamService.CreateSanpham(v);
        }
      });
     const disableItem = listId3.map(async (v: any) => {
        const item = this._SanphamService.ListSanpham().find((v1) => v1.masp === v);
        item.isActive = false;
        await this._SanphamService.updateSanpham(item);
      });
      Promise.all([...createuppdateitem, ...disableItem]).then(() => {
        this._snackBar.open('Cập Nhật Thành Công', '', {
          duration: 1000,
          horizontalPosition: 'end',
          verticalPosition: 'top',
          panelClass: ['snackbar-success'],
        });
       // window.location.reload();
      });
  }
  async ImporExcel(event: any) {
  const data = await readExcelFile(event)
  this.DoImportData(data);
  }   
  ExportExcel(data:any,title:any) {
    const dulieu = data.map((v: any) => ({
      title: v.title,
      title2: v.title2,
      subtitle: v.subtitle,
      masp: v.masp,
      giagoc: v.giagoc,
      dvt: v.dvt,
      soluong: v.soluong,
      soluongkho: v.soluongkho,
      haohut: v.haohut,
      ghichu: v.ghichu,
    }));
    writeExcelFile(dulieu,title);
  }
  trackByFn(index: number, item: any): any {
    return item.id; // Use a unique identifier
  }



  initSP = [
    {
        "manccold": "V100049",
        "mancc": "TG-NCC0001",
        "tenncc": "Tỏi Bình minh",
        "tensp1": "Bắp Cải Tím",
        "tensp2": "Hành Tím Củ",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100050",
        "mancc": "TG-NCC0002",
        "tenncc": "CHỊ BÉ RAU MUỐNG",
        "tensp1": "Cải Rổ",
        "tensp2": "Rau Đay",
        "tensp3": "Rau Dền Xanh",
        "tensp4": "Rau Nhút",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100034",
        "mancc": "TG-NCC0003",
        "tenncc": "Năm Nấm",
        "tensp1": "Bắp Non Tươi",
        "tensp2": "Bắp Non Tươi ( Loại 1)",
        "tensp3": "Bông Thiên Lý",
        "tensp4": "Cải Mầm (100g)",
        "tensp5": "Đậu Hủ Non Ichiban",
        "tensp6": "Đậu Hủ Trắng Ichiban",
        "tensp7": "Hạt Sen Tươi",
        "tensp8": "Ngó Sen Chẻ",
        "tensp9": "Ngó Sen Ngâm Chua",
        "tensp10": "Rau Muống Mầm",
        "tensp11": "Tiêu Xanh Tươi",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100020",
        "mancc": "TG-NCC0004",
        "tenncc": "A Bằng Cần Nước",
        "tensp1": "Bạc hà",
        "tensp2": "Lá Cách",
        "tensp3": "Bắp chuối bào",
        "tensp4": "Thân chuối bào",
        "tensp5": "Rau muống bào",
        "tensp6": "Cần nước",
        "tensp7": "Lá Trâm Ổi",
        "tensp8": "Bắp nếp",
        "tensp9": "Lá cóc",
        "tensp10": "Rau muống cọng",
        "tensp11": "Quế vị (xá xị)",
        "tensp12": "Bông súng",
        "tensp13": "Kèo nèo (bó)",
        "tensp14": "Rau đắng",
        "tensp15": "Chuối chát",
        "tensp16": "Lá Giang (bó)",
        "tensp17": "Rau nước mát",
        "tensp18": "Lá mơ",
        "tensp19": "Chuối xanh",
        "tensp20": "Nha đam",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100010",
        "mancc": "TG-NCC0005",
        "tenncc": "Bảy Đẩu",
        "tensp1": "Cải Sậy ",
        "tensp2": "Củ Cải Muối",
        "tensp3": "Củ Gừng",
        "tensp4": "Củ Nén",
        "tensp5": "Củ Riềng",
        "tensp6": "Hành Phi",
        "tensp7": "Hành Tím Bào",
        "tensp8": "Hành Tím VN nguyên Củ",
        "tensp9": "Măng Chua Trắng",
        "tensp10": "Nấm Mèo",
        "tensp11": "Ngải Bún",
        "tensp12": "Sả Bào",
        "tensp13": "Sả Xay",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100018",
        "mancc": "TG-NCC0006",
        "tenncc": "Gái Hành Lá",
        "tensp1": "Hẹ lá",
        "tensp2": "Cần tàu",
        "tensp3": "Ngò om",
        "tensp4": "Rau răm",
        "tensp5": "Rau kinh giới",
        "tensp6": "Thì là",
        "tensp7": "Húng quế",
        "tensp8": "Rau diếp cá",
        "tensp9": "Húng cây",
        "tensp10": "Rau tía tô",
        "tensp11": "Ngò gai",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100037",
        "mancc": "TG-NCC0007",
        "tenncc": "Trung Đậu Bắp",
        "tensp1": "Bắp cải trái tim",
        "tensp2": "Xà lách son Đà Lạt",
        "tensp3": "Cà pháo xanh",
        "tensp4": "Đậu rồng",
        "tensp5": "Su Su",
        "tensp6": "Cà rốt ĐaLat",
        "tensp7": "Xà lách búp ĐL",
        "tensp8": "Cà rốt ĐaLat (củ lớn)",
        "tensp9": "Củ dền lớn",
        "tensp10": "Cà pháo",
        "tensp11": "Đậu đũa xanh",
        "tensp12": "Cà Pháo Tím",
        "tensp13": "Cà chua",
        "tensp14": "Cà chua hườm",
        "tensp15": "Cà Chua Lớn",
        "tensp16": "Cà pháo lớn",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100095",
        "mancc": "TG-NCC0008",
        "tenncc": "CHÍN ỚT CHUÔNG",
        "tensp1": "Xà lách búp mỹ",
        "tensp2": "Xà lách Big Frisse",
        "tensp3": "Xà lách Rocket",
        "tensp4": "Củ cải đỏ (Radis)",
        "tensp5": "Củ sen",
        "tensp6": "Bông cải xanh Baby",
        "tensp7": "Măng tây xanh",
        "tensp8": "Măng tây xanh (lớn)",
        "tensp9": "Cà chua bi",
        "tensp10": "Lá é",
        "tensp11": "Cà chua Beef",
        "tensp12": "Đọt su su",
        "tensp13": "Rau rừng Gia Lai",
        "tensp14": "Bí nụ",
        "tensp15": "Ớt đà lạt (đỏ)",
        "tensp16": "Cần tây",
        "tensp17": "Cà chua socola",
        "tensp18": "Hành Paro",
        "tensp19": "Đậu cove trắng",
        "tensp20": "Ớt đà lạt (vàng)",
        "tensp21": "Đậu bo tươi",
        "tensp22": "Củ hồi",
        "tensp23": "Cải Kale",
        "tensp24": "Ớt đà lạt (xanh)",
        "tensp25": "Cà rốt baby",
        "tensp26": "Ngò tây",
        "tensp27": "Chanh Dây",
        "tensp28": "Xà lách romain",
        "tensp29": "Su su baby",
        "tensp30": "Quế tây"
    },
    {
        "manccold": "V100015",
        "mancc": "TG-NCC0010",
        "tenncc": "Nga Nấm",
        "tensp1": "Nấm Rơm",
        "tensp2": "Nấm Bào Ngư Trắng",
        "tensp3": "Nấm Bào Ngư Xám",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100022",
        "mancc": "TG-NCC0011",
        "tenncc": "Cô Tí Chanh",
        "tensp1": "Chanh ĐaLat",
        "tensp2": "Chanh Giấy",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100051",
        "mancc": "TG-NCC0012",
        "tenncc": "BẰNG KHOAI",
        "tensp1": "Khoai môn sọ",
        "tensp2": "Khoai môn cao",
        "tensp3": "Khoai mỡ",
        "tensp4": "Bí đỏ tròn",
        "tensp5": "Bí đỏ hồ lô",
        "tensp6": "Khoai lang mật",
        "tensp7": "Khoai mì",
        "tensp8": "Khoai lang nhật",
        "tensp9": "Khoai môn sáp",
        "tensp10": "Củ sắn",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100032",
        "mancc": "TG-NCC0013",
        "tenncc": "Dưa Hấu",
        "tensp1": "Dưa Hấu",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100031",
        "mancc": "TG-NCC0014",
        "tenncc": "Thơm",
        "tensp1": "Thơm Gọt",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100078",
        "mancc": "TG-NCC0016",
        "tenncc": "LY ĐL",
        "tensp1": "Cải Kale",
        "tensp2": "Rosemary (Hương Thảo)",
        "tensp3": "Xà lách búp mỹ",
        "tensp4": "Quế tây",
        "tensp5": "Xà lách Radichio",
        "tensp6": "Hoadécor",
        "tensp7": "Ngò tây",
        "tensp8": "Thyme (Xạ Hương)",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100151",
        "mancc": "TG-NCC0018",
        "tenncc": "MẠNH ĐẬU HỦ",
        "tensp1": "Miếng Trắng",
        "tensp2": "Miếng Chiên",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100071",
        "mancc": "TG-NCC0019",
        "tenncc": "SANG ĐL",
        "tensp1": "Bó xôi (Nhà Lồng)",
        "tensp2": "Xà lách carol",
        "tensp3": "Cần tây",
        "tensp4": "Hành Paro",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100164",
        "mancc": "TG-NCC0020",
        "tenncc": "Triệu Chanh",
        "tensp1": "Chanh không hạt",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100088",
        "mancc": "TG-NCC0021",
        "tenncc": "TUYẾN TÂM",
        "tensp1": "Lá chuối",
        "tensp2": "Bông điên điển",
        "tensp3": "Bắp chuối hột nguyên trái",
        "tensp4": "Bông so đũa",
        "tensp5": "Rau càng cua",
        "tensp6": "Lá trà",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100087",
        "mancc": "TG-NCC0022",
        "tenncc": "DIÊN CỦ HỦ DỪA",
        "tensp1": "Củ Hủ Dừa",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100122",
        "mancc": "TG-NCC0026",
        "tenncc": "OANH CÀ RỐT",
        "tensp1": "Cà rốt ĐaLat (củ lớn)",
        "tensp2": "Củ dền lớn",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100060",
        "mancc": "TG-NCC0027",
        "tenncc": "GIÁ",
        "tensp1": "Giá Tươi",
        "tensp2": "Giá Sạch",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100161",
        "mancc": "TG-NCC0028",
        "tenncc": "GIANG BẮP",
        "tensp1": "Bắp mỹ trái",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100103",
        "mancc": "TG-NCC0029",
        "tenncc": "TRÁI CÂY PHƯỢNG HẰNG",
        "tensp1": "Xoài keo",
        "tensp2": "Ổi không hạt",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100014",
        "mancc": "TG-NCC0030",
        "tenncc": "Thuận Son",
        "tensp1": "Xà Lách Son Nhỏ",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100085",
        "mancc": "TG-NCC0031",
        "tenncc": "ANH ĐĂNG",
        "tensp1": "Lá sen tươi",
        "tensp2": "Chanh thái",
        "tensp3": "Lá cari",
        "tensp4": "Lá chanh Thái",
        "tensp5": "Lá hương nhu",
        "tensp6": "Lá cẩm",
        "tensp7": "Lá bạc hà",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100068",
        "mancc": "TG-NCC0032",
        "tenncc": "Tư bún",
        "tensp1": "Bún Nhỏ",
        "tensp2": "Bánh Canh Bột Gạo ",
        "tensp3": "Bánh Ướt",
        "tensp4": "Bánh Phở",
        "tensp5": "Bún Bò",
        "tensp6": "Hủ Tiếu Dai",
        "tensp7": "Mì Quảng ",
        "tensp8": "Bánh Hỏi",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100104",
        "mancc": "TG-NCC0033",
        "tenncc": "PHƯỢNG RAU RỪNG",
        "tensp1": "Rau rừng gia lai",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100070",
        "mancc": "TG-NCC0034",
        "tenncc": "NAM TÂM ĐL",
        "tensp1": "Cà chua bi",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100202",
        "mancc": "TG-NCC0035",
        "tenncc": "BẢO VÕ ĐL",
        "tensp1": "Xà lách Rocket",
        "tensp2": "Ngò tây",
        "tensp3": "Cà rốt baby",
        "tensp4": "Xà lách Big Frisse",
        "tensp5": "Xà lách lolo tím",
        "tensp6": "Củ cải đỏ (Radis)",
        "tensp7": "Xà lách romain",
        "tensp8": "Quế tây",
        "tensp9": "Xà lách Radichio",
        "tensp10": "Củ hồi",
        "tensp11": "Hoa décor (Hoa trang trí 12g)",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100201",
        "mancc": "TG-NCC0036",
        "tenncc": "HUY CẢI THẢO ĐL",
        "tensp1": "Bắp cải trắng",
        "tensp2": "Cà tím",
        "tensp3": "Cải thảo",
        "tensp4": "Dưa leo baby",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100111",
        "mancc": "TG-NCC0037",
        "tenncc": "TUYỀN ĐÀ LẠT",
        "tensp1": "Hành Paro",
        "tensp2": "Bí ngòi xanh",
        "tensp3": "Bí ngòi vàng",
        "tensp4": "Hành tây",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100064",
        "mancc": "TG-NCC0038",
        "tenncc": "TUYỀN BÔNG BÍ",
        "tensp1": "Bông bí",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100086",
        "mancc": "TG-NCC0039",
        "tenncc": "SANG ĐU ĐỦ",
        "tensp1": "Đu Đủ Xanh",
        "tensp2": "Đu đủ hườm",
        "tensp3": "Chanh không hạt",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100099",
        "mancc": "TG-NCC0040",
        "tenncc": "Ái Măng Tây",
        "tensp1": "Măng tây xanh",
        "tensp2": "Lá é",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100147",
        "mancc": "TG-NCC0041",
        "tenncc": "ĐẬU HỦ CP",
        "tensp1": "Đậu hủ trứng 220gr",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100055",
        "mancc": "TG-NCC0042",
        "tenncc": "Nấm Sao Việt",
        "tensp1": "Nấm Đông Cô Tươi",
        "tensp2": "Nấm Đùi Gà",
        "tensp3": "Nấm Đùi Gà Baby",
        "tensp4": "Nấm Kim Châm Tươi",
        "tensp5": "Nấm Linh Chi Đen(125g)",
        "tensp6": "Xà lách lolo Xanh",
        "tensp7": "Nấm linh chi trắng (125g)",
        "tensp8": "Nấm linh chi đen (125g)",
        "tensp9": "Nấm hải sản (kg)",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100108",
        "mancc": "TG-NCC0043",
        "tenncc": "CHANH VÀNG PHỤNG HOÀNG",
        "tensp1": "Chanh vàng",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100167",
        "mancc": "TG-NCC0044",
        "tenncc": "DUNG TRÚC - TRẦN GIA",
        "tensp1": "Đậu Bắp",
        "tensp2": "Dưa Leo",
        "tensp3": "Khổ Qua",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100168",
        "mancc": "TG-NCC0045",
        "tenncc": "TỎI HÒA CHU",
        "tensp1": "Tỏi Lột",
        "tensp2": "Tỏi Khô",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100172",
        "mancc": "TG-NCC0046",
        "tenncc": "HÀNH TỎI HÒA CHU",
        "tensp1": "Hành tây",
        "tensp2": "Hành tím củ",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100171",
        "mancc": "TG-NCC0047",
        "tenncc": "TUẤN THANH - CÀ RỐT",
        "tensp1": "Cà rốt",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100179",
        "mancc": "TG-NCC0050",
        "tenncc": "BÌNH L2-18",
        "tensp1": "Bắp cải trắng",
        "tensp2": "Xà lách lolo xanh",
        "tensp3": "Cải thảo",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100182",
        "mancc": "TG-NCC0051",
        "tenncc": "MƠ - THÚY N2-18",
        "tensp1": "Bắp Chuối Nguyên Trái",
        "tensp2": "Lá Cóc ",
        "tensp3": "Sao Nhái",
        "tensp4": "Lá Lốt",
        "tensp5": "Rau rừng Tây Ninh",
        "tensp6": "ĐInh Lăng",
        "tensp7": "Trâm ổi",
        "tensp8": "Khế Xanh",
        "tensp9": "Bắp chuối bào",
        "tensp10": "Rau muống bào",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100184",
        "mancc": "TG-NCC0052",
        "tenncc": "CHÂU NGA - TRẦN GIA",
        "tensp1": "Bông Cải Trắng",
        "tensp2": "Bông Cải Xanh",
        "tensp3": "Cải Thảo",
        "tensp4": "Xà lách lolo xanh",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100185",
        "mancc": "TG-NCC0053",
        "tenncc": "TÂM TỎI ỚT",
        "tensp1": "Ớt Batri (Cay)",
        "tensp2": "Tiêu đen hạt",
        "tensp3": "Tỏi phi",
        "tensp4": "Hành tím lột vỏ TQ",
        "tensp5": "Tỏi lột sạch (cắt đầu)",
        "tensp6": "Hành tím bắc lột",
        "tensp7": "Tiêu đen xay",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100189",
        "mancc": "TG-NCC0056",
        "tenncc": "THỪA HÀNH NGÒ",
        "tensp1": "Hành Lá",
        "tensp2": "Ngò rí",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100191",
        "mancc": "TG-NCC0057",
        "tenncc": "QUẢNG VỰA ỚT",
        "tensp1": "Bó xôi (Nhà Lồng)",
        "tensp2": "Xà lách búp mỹ",
        "tensp3": "Xà lách romain",
        "tensp4": "Dưa leo nhật",
        "tensp5": "Đậu Hà Lan",
        "tensp6": "Bí ngòi xanh",
        "tensp7": "Xà lách lolo tím",
        "tensp8": "Ớt sừng xanh",
        "tensp9": "Xà lách carol",
        "tensp10": "Cải Cầu Vồng",
        "tensp11": "Tần ô",
        "tensp12": "Lá cây nhíp (lá mè)",
        "tensp13": "Xà lách Big Frisse",
        "tensp14": "Xà lách Radichio",
        "tensp15": "Rosemary (Hương thảo)",
        "tensp16": "Bí ngòi vàng",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100192",
        "mancc": "TG-NCC0058",
        "tenncc": "BẢO TIÊN - TRẦN GIA",
        "tensp1": "Cải ngọt",
        "tensp2": "Đọt rau lang",
        "tensp3": "Cải Hongkong(Cai ngong)",
        "tensp4": "Rau bù ngót",
        "tensp5": "Cải xanh con",
        "tensp6": "Mồng tơi",
        "tensp7": "Cải bẹ xanh có gốc",
        "tensp8": "Cải nhún",
        "tensp9": "Cải thìa",
        "tensp10": "Rau muống lá",
        "tensp11": "Hành hương làm sạch",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100193",
        "mancc": "TG-NCC0059",
        "tenncc": "PHƯỢNG LA",
        "tensp1": "Cải thìa",
        "tensp2": "Dưa leo",
        "tensp3": "Bầu xanh",
        "tensp4": "Mướp hương",
        "tensp5": "Hẹ lá",
        "tensp6": "Thì là",
        "tensp7": "Đậu đũa xanh",
        "tensp8": "Ngò om",
        "tensp9": "Bí đao",
        "tensp10": "Khổ qua",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100194",
        "mancc": "TG-NCC0061",
        "tenncc": "TUẤN SẢ LONG AN",
        "tensp1": "Sả cây",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100204",
        "mancc": "TG-NCC0062",
        "tenncc": "NAM RAU MUỐNG",
        "tensp1": "Rau muống cọng",
        "tensp2": "Cải thìa",
        "tensp3": "Cải ngọt",
        "tensp4": "Rau muống lá",
        "tensp5": "Cải Hongkong(Cai ngong)",
        "tensp6": "Rau muống hạt",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100205",
        "mancc": "TG-NCC0063",
        "tenncc": "CÔ PHƯỢNG ỔI",
        "tensp1": "Chanh Dây",
        "tensp2": "Tắc trái",
        "tensp3": "Cam tươi",
        "tensp4": "Thanh long ruột trắng",
        "tensp5": "Dưa hấu",
        "tensp6": "Xoài Keo",
        "tensp7": "Ổi không hạt",
        "tensp8": "Chanh không hạt",
        "tensp9": "Thanh long ruột đỏ",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100207",
        "mancc": "TG-NCC0064",
        "tenncc": "THI CỦ CẢI",
        "tensp1": "Cà Rốt",
        "tensp2": "Củ Cải Trắng (Loại 1)",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100208",
        "mancc": "TG-NCC0065",
        "tenncc": "TÍ HÀNH HƯƠNG",
        "tensp1": "Hành hương làm sạch",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100131",
        "mancc": "TG-NCC0066",
        "tenncc": "Điền Nga",
        "tensp1": "Bao Zin 40",
        "tensp2": "Bao Trắng 30",
        "tensp3": "Bao Trắng 25",
        "tensp4": "Bao Zin To",
        "tensp5": "Bao Đựng Giá 30",
        "tensp6": "Bao Trắng 40",
        "tensp7": "Băng keo trong",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100091",
        "mancc": "TG-NCC0067",
        "tenncc": "CÔ PHÚC LOLO XANH",
        "tensp1": "Xà Lách Lolo Xanh",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100219",
        "mancc": "TG-NCC0070",
        "tenncc": "Thúy Sen",
        "tensp1": "Bông sen",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100222",
        "mancc": "TG-NCC0078",
        "tenncc": "DUNG LÁ MÈ - ĐL",
        "tensp1": "Lá cây nhíp (lá mè)",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100176",
        "mancc": "TG-NCC0161",
        "tenncc": "TRỨNG VĨNH THÀNH",
        "tensp1": "Trứng Gà ",
        "tensp2": "Trứng Vịt Muối",
        "tensp3": "Trứng cút",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100228",
        "mancc": "TG-NCC0186",
        "tenncc": "BÉ NĂM PHƯỚC HẬU",
        "tensp1": "Cải bẹ xanh có gốc",
        "tensp2": "Cải Ngọt",
        "tensp3": "Mồng Tơi",
        "tensp4": "Ngò Om",
        "tensp5": "Rau Muống Hạt",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100232",
        "mancc": "TG-NCC0189",
        "tenncc": "DƯƠNG THƠM",
        "tensp1": "Tắc trái",
        "tensp2": "Thơm trái xanh",
        "tensp3": "Chanh không hạt",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100233",
        "mancc": "TG-NCC0190",
        "tenncc": "DIỄM BẮP GIA LAI",
        "tensp1": "Bắp mý trái",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100225",
        "mancc": "TG-NCC0214",
        "tenncc": "Phương ĐD - ĐL",
        "tensp1": "Xà lách lolo xanh",
        "tensp2": "Cà Chua Lớn",
        "tensp3": "Ngò rí",
        "tensp4": "Hành tây",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    },
    {
        "manccold": "V100226",
        "mancc": "TG-NCC0215",
        "tenncc": "LONG ĐL",
        "tensp1": "Tần ô",
        "tensp2": "",
        "tensp3": "",
        "tensp4": "",
        "tensp5": "",
        "tensp6": "",
        "tensp7": "",
        "tensp8": "",
        "tensp9": "",
        "tensp10": "",
        "tensp11": "",
        "tensp12": "",
        "tensp13": "",
        "tensp14": "",
        "tensp15": "",
        "tensp16": "",
        "tensp17": "",
        "tensp18": "",
        "tensp19": "",
        "tensp20": "",
        "tensp21": "",
        "tensp22": "",
        "tensp23": "",
        "tensp24": "",
        "tensp25": "",
        "tensp26": "",
        "tensp27": "",
        "tensp28": "",
        "tensp29": "",
        "tensp30": ""
    }
]

}




function memoize() {
  return function (
    target: any,
    propertyKey: string,
    descriptor: PropertyDescriptor
  ) {
    const originalMethod = descriptor.value;
    const cache = new Map();

    descriptor.value = function (...args: any[]) {
      const key = JSON.stringify(args);
      if (cache.has(key)) {
        return cache.get(key);
      }
      const result = originalMethod.apply(this, args);
      cache.set(key, result);
      return result;
    };

    return descriptor;
  };
}

function Debounce(delay: number = 300) {
  return function (
    target: any,
    propertyKey: string,
    descriptor: PropertyDescriptor
  ) {
    const originalMethod = descriptor.value;
    let timeoutId: any;

    descriptor.value = function (...args: any[]) {
      clearTimeout(timeoutId);
      timeoutId = setTimeout(() => {
        originalMethod.apply(this, args);
      }, delay);
    };

    return descriptor;
  };
}

